### ISSUE TITLE
Disabling drag & drop is not working correctly

### ISSUE THREAD

**Issue by awulkan** [hejianxian/vddl#17]
Items disappear under certain circumstances if you disable drag & drop and then drag them.

**Steps to reproduce**
1. Go to this page: http://hejx.space/vddl-demo/#/nested
2. Click the red 'disable' button.
3. Select the text inside of an item and drag it.

**Temporary solution**
I managed to get around this by adding this class to my css:
```css
.disable-drag {
  user-select: none;
  pointer-events: none; /* Not needed but prevents visual effect of dragging an item. */
}
```
And then adding
```css
:class="{'disable-drag': disable}"
```

To my nested list like this
```<vddl-draggable class="group-item" :class="{'disable-drag': disable}"```
and this
```<vddl-list class="group-body" :class="{'disable-drag': disable}"```
