### ISSUE TITLE
Support horizontal and vertical simultaneously

### ISSUE THREAD

**Issue by pSchaub** [hejianxian/vddl#21]
Is it possible to support horizontal and vertical on the same container?
I want to drag containers from the "vertical" list inside the "horizontal" list.
Can you provide an example?

**Comment by hejianxian** [comment]
Weekends, I try it.

**Comment by hejianxian** [comment]
@pSchaub Hi.

I tried it, just change the style of the item inside the `Container`. Set `float: left`, and set the width to `50%`, and don't forget to change the style of the placeholder in the container.

```css
.container .item, .container .vddl-placeholder {
  float: left;
  width: 50%;
}
```
